### ISSUE TITLE
Types not enabled. types value in package.json is incorrect.

### ISSUE THREAD

**Issue by vinnieking06** [arthurfiorette/axios-cache-interceptor#115]
In the package.json, the types value references a file that does not exist, "./dist/index.ts". Changing to "./dist/index.d.ts" fixes the issue for me.

![Screen Shot 2022-01-13 at 3 07 40 PM](https://user-images.githubusercontent.com/18544837/149416668-a10c3ad4-aa6c-42a3-ac1a-5ccf750af97c.png)

**Comment by arthurfiorette** [comment]
I think that was fixed right now. See at 0.8.1

**Comment by vinnieking06** [comment]
Will give it a try, thank you

**Comment by vinnieking06** [comment]
That fixes it for me. Thanks
