### ISSUE TITLE
Post requests cache is not busted when data values change (swap data for params in defaultKeyGenerator)

### ISSUE THREAD

**Issue by vinnieking06** [arthurfiorette/axios-cache-interceptor#116]
In defaultKeyGenerator, the params value is used to generate the key. The problem is that params is undefined on all requests that I've seen, so post requests end up getting cached, even when their bodies have different data. I recommend instead pulling in the data value and including that as part of the key. This guarantees that the cache will be broken if the post request's body changes. The post request body will come in as the data value.
![Screen Shot 2022-01-13 at 4 09 33 PM](https://user-images.githubusercontent.com/18544837/149423213-b09947ac-385a-4703-917d-2ad2dd39a87e.png)

**Comment by arthurfiorette** [comment]
Fixed.

Can you test with the new contents of `key-generator.test.ts`?

https://github.com/arthurfiorette/axios-cache-interceptor/blob/6f9ef36e75c2215f3079347e1bcb21ca2f225441/src/util/key-generator.ts

**Comment by arthurfiorette** [comment]
Tomorrow I'll see how this should take into account the `request.paramsSerializer`.

Looking at the `AxiosRequestConfig` types, there are probably more options that must generate different keys, like `withCredentials` and etc.

```ts
  transformRequest?: AxiosRequestTransformer | AxiosRequestTransformer[];
  transformResponse?: AxiosResponseTransformer | AxiosResponseTransformer[];
  headers?: AxiosRequestHeaders;
  paramsSerializer?: (params: any) => string;
  timeout?: number;
  timeoutErrorMessage?: string;
  withCredentials?: boolean;
  adapter?: AxiosAdapter;
  auth?: AxiosBasicCredentials;
  responseType?: ResponseType;
  xsrfCookieName?: string;
  xsrfHeaderName?: string;
  onUploadProgress?: (progressEvent: any) => void;
  onDownloadProgress?: (progressEvent: any) => void;
  maxContentLength?: number;
  validateStatus?: ((status: number) => boolean) | null;
  maxBodyLength?: number;
  maxRedirects?: number;
  socketPath?: string | null;
  httpAgent?: any;
  httpsAgent?: any;
  proxy?: AxiosProxyConfig | false;
  cancelToken?: CancelToken;
  decompress?: boolean;
  transitional?: TransitionalOptions;
  signal?: AbortSignal;
  insecureHTTPParser?: boolean;
```

**Comment by vinnieking06** [comment]
Thank you! I agree on your last comment. Headers.Authorization would also be a good one. If the consumer wants to get really picky, they can always pass in their own keyGenerator.

**Comment by arthurfiorette** [comment]
Tomorrow i am going to publish `0.8.2` with this fix, ok?

**Comment by vinnieking06** [comment]
Yep, have a good night!

**Comment by vinnieking06** [comment]
@arthurfiorette I opted to just pass in my own key generator, since we have other needs, like cache busting on authorization token changes. Thank you for your help and attentiveness! This is a great little package.

**Comment by arthurfiorette** [comment]
Sorry, I couldn't get to this project till now.

I did some research because i was worried about the key length beeing to big, since the data is now included. Looked at some npm packages to do object hash and didn't was satisfied. There was too much code or they generates weak hashes.

Got into my old Java days with object hashcode and created my own.

It is around 500 bytes and i liked it, so i'll publish under another package name and import here.

The 0.8.2 is going to include it and will be something like that: 

```ts
hashCode({
  url: baseURL + (baseURL && url ? '/' : '') + url,
  method: method ? method.toLowerCase() : 'get',
  params,
  data
});
```

I ended up choosing to not include headers and other fields, because it would be too specific, this way it will be easy to extend the key generator and maintain "standarts" with other implementations.

I'll leave this issue open until 0.8.2 is published.

**Comment by vinnieking06** [comment]
Sounds good, thanks for the update!

**Comment by arthurfiorette** [comment]
https://github.com/arthurfiorette/axios-cache-interceptor/commit/9379fce10053348cf48e8a225dbbdb12e145dbcf 🎉🎉

I was also creating my own `keyGenerator` at some projects. So i made things a little easier with `buildKeyGenerator`. This function detects if the request config has and id, remove trailling slashes from `url`, `baseURL` and has space to future changes without breaking users implementations.

Documentation: https://axios-cache-interceptor.js.org/#/pages/request-id?id=joining-requests

**Comment by arthurfiorette** [comment]
`0.8.2`, here we go
