### ISSUE TITLE
axios 0.26.0 warning

### ISSUE THREAD

**Issue by spacedawwwg** [arthurfiorette/axios-cache-interceptor#145]
getting a `➤ YN0060: │ package provides axios (p027d5) with version 0.26.0, which doesn't satisfy what axios-cache-interceptor requests`

peer deps of axios-cache-interceptor require ^0.25.0, so not sure why this warning is arising?

**Comment by arthurfiorette** [comment]
Hmm, have you updated axios to v0.26, too?

**Comment by spacedawwwg** [comment]
```
 "dependencies": {
    "@netlify/functions": "^1.0.0",
    "@sanity/image-url": "^1.0.1",
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.18",
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/compiler-sfc": "^3.2.31",
    "@vue/server-renderer": "^3.2.31",
    "@vue/test-utils": "next",
    "axios": "^0.26.0",
    "axios-cache-interceptor": "^0.8.9",
    "consola": "^2.15.3",
    "cross-env": "^7.0.3",
    "defu": "^5.0.1",
    "dotenv": "^16.0.0",
    "express": "^4.17.2",
    "focus-trap": "^6.7.3",
    "focus-trap-vue": "next",
    "focus-visible": "^5.2.0",
    "fs-extra": "^10.0.0",
    "glob": "^7.2.0",
    "glob-promise": "^4.2.2",
    "purgecss": "^4.1.3",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5",
    "vite": "^2.8.3",
    "vite-imagetools": "^4.0.3",
    "vite-plugin-environment": "^1.1.0",
    "vite-plugin-ssr": "^0.3.53",
    "vite-tsconfig-paths": "^3.4.0",
    "vue": "^3.2.31",
    "window-resize-subject": "^1.5.0"
  },
  "devDependencies": {
    "@types/jest": "^27.4.0",
    "@vue/vue3-jest": "^27.0.0-alpha.4",
    "esbuild": "^0.14.21",
    "esbuild-runner": "^2.2.1",
    "eslint": "^8.9.0",
    "jest": "^27.5.1",
    "rimraf": "^3.0.2",
    "serve": "^13.0.2"
  }
```

**Comment by arthurfiorette** [comment]
Well, I'm not sure too.

I'll remove the peerDependencies section...

If someone from the future knows why, please tell us <3

**Comment by arthurfiorette** [comment]
@spacedawwwg, can you try with `v0.8.10`?

**Comment by spacedawwwg** [comment]
all good, my friend!

**Comment by goodefroi** [comment]
> Well, I'm not sure too.
> 
> I'll remove the peerDependencies section...
> 
> If someone from the future knows why, please tell us <3

Likely because the [Semver spec doesn't consider `0.y.z` versions as having a stable API](https://semver.org/#spec-item-4), so a change from `0.25.0` to `0.26.0` could introduce breaking changes. The problem shouldn't have arisen for a hypothetical bump from `axios@1.25.0` to `axios@1.26.0`.
