### ISSUE TITLE
Incorrect URL is being built when using relative paths.

### ISSUE THREAD

**Issue by Chandu** [arthurfiorette/axios-cache-interceptor#161]
Hi,
In my application I have the backend serve a static page at a specific path `/clients/index.html` and client api root is `/clients/api`
Once the  `/clients/index.html` is loaded, I need to get client information using the end point `/clients/api/info`.

I am using express for the backend and react for the frontend leveraging `axios` along with the `axios-cache-interceptor`.

However when using the `axios` instance (decorated by `setupCache`) with the `baseURL`  set to : '/clients/api' and the reqeust url set to `/info`,  I am noticing a 404 error in the console. 

 Page URL: http://localhost:3010/clients/index.html
 Clients Information Endpoint: http://localhost:3010/clients/api/info

**Working code:**
```
var clientsApi = axios.create({
    baseURL: '/clients/api'
  });

  clientsApi.get('/info').then(a => {
    console.log('Received response: ', a.data);
  }).catch(err => {
    console.log('Error using vanialla axios');
    console.error(err);
  });
```
**Failing code: **
```
var clientsApiWithCache = AxiosCacheInterceptor.setupCache(axios.create({
    baseURL: '/clients/api'
  }));

  
  clientsApiWithCache.get('/info').then(a => {
    console.log('Received response using setupCache: ', a.data);
  }).catch(err => {
    console.log('Error using setupCache:');
    console.error(err);
  });
```

I have debugged the code and see that the issue occurs because of this line: https://github.com/arthurfiorette/axios-cache-interceptor/blob/dc27cd5b53b2d8847e8821a4607c7e3f25927bbc/src/util/key-generator.ts#L49 

Any specific reason for trimming the slashes from the `baseURL` and `url`? 

The repo @ https://github.com/Chandu/axios-cache-interceptor-relative-base-path-issue can be used to reproduce the issue (I haven't used react in this repo for simpler setup, but the error can be reproduced ).

**Screenshot showing the code/error**

![image](https://user-images.githubusercontent.com/261027/156559903-4d005f08-176b-465f-a87f-b147825c953a.png)

**Comment by arthurfiorette** [comment]
When I get home, I'll se it. Just a sec

**Comment by arthurfiorette** [comment]
> Any specific reason for trimming the slashes from the baseURL and url?

Yes, but not in the current way. :p

These changes should only be kept within the scope of the keyGenerator. Fixing it...

**Comment by arthurfiorette** [comment]
Tested it and everything worked as intended. I'll release 0.9.3 tomorrow.

If everything seems good, can you close this issue?

**Comment by Chandu** [comment]
Awesome Thanks @arthurfiorette 
Will check with the latest version once released.

**Comment by arthurfiorette** [comment]
@Chandu [**`v0.9.3`**](https://github.com/arthurfiorette/axios-cache-interceptor/releases/tag/v0.9.3)

**Comment by Chandu** [comment]
Thanks @arthurfiorette.
I am closing this issue as I was to verify the fix successfully
