### ISSUE TITLE
Custom BuildStorage example is wrongly typed

### ISSUE THREAD

**Issue by arnaud9145** [arthurfiorette/axios-cache-interceptor#169]
Hello !

Thanks for this lib, I wanted to use it with redis to store the cache, and followed that example : https://axios-cache-interceptor.js.org/#/pages/storages?id=creating-your-own-storage

But when I implemented it, I got an error from typescript :
<img width="714" alt="Capture d’écran 2022-03-11 à 11 38 06" src="https://user-images.githubusercontent.com/1856194/157851404-19f82d86-5578-4486-8c54-28f960c7ff43.png">

I think I figured out what's wrong : 
- Redis expects a string to save, so in the set function we Stringify the value.
- When we get the value from redis in the get function and give it to the buildStorage, we do not parse it. Either the parse is done by the buildStorage and the get function is wrongly typed, or we have to manually parse the value returned by Redis before returning it : 
 
<img width="460" alt="Capture d’écran 2022-03-11 à 11 40 49" src="https://user-images.githubusercontent.com/1856194/157851849-6464063d-f2a6-479b-bada-8c3ff5ba3978.png">

If I'm correct, maybe adjust the documentation for futur users ;) If I'm wrong, what am I missing ?

**Comment by arthurfiorette** [comment]
Yep, you are 100% correct.
I don't know how I let this get his way into the documentation. Looking forward, seems that this even may be the fix for #165.

**Comment by himasimplisafe** [comment]
@arnaud9145 i am also using redis storage, do you mind to put an example about how you are using redisStorage when setupCache and do you need to await on buildStorage?

**Comment by arthurfiorette** [comment]
I've just updated the redis example in the documentation.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/docs/pages/storages.md#creating-your-own-storage

**Comment by arthurfiorette** [comment]
@arnaud9145 can I close this issue?
