### ISSUE TITLE
How to cache:false as a global configuration

### ISSUE THREAD

**Issue by prince272** [arthurfiorette/axios-cache-interceptor#173]

**Comment by arthurfiorette** [comment]
Hey. I haven't tested this before, but i guess you can just set it false like this:

```js
let axios = setupCache(...);

axios.defaults.cache = false;
```

**Comment by arthurfiorette** [comment]
@prince272 does this solve your problem?

**Comment by arthurfiorette** [comment]
I'll close this issue as you didn't provide much information or awnsered anything. You can open another issue, if needed. :p
