### ISSUE TITLE
Uncaught (in promise) Error: Use buildStorage() function at j (create.ts:47:1)

### ISSUE THREAD

**Issue by KevinFreistroffer** [arthurfiorette/axios-cache-interceptor#233]
### Description
This is in a React application written in TypeScript.

We're using `buildWebStorage(localStorage)`. Occasionally the localStorage cache state will stay in `loading`. The network request is successful with a 200 status code, and the expected response data. To debug this, we're enabling development mode, by importing setupCache from `axios-cache-interceptor/dev `, however the following error shows:

![unnamed](https://user-images.githubusercontent.com/4844840/166810537-5d7c3882-2926-438b-85f0-847d87a8e8f8.png)

<img width="643" alt="Screen Shot 2022-05-04 at 12 15 25 PM" src="https://user-images.githubusercontent.com/4844840/166810542-269f5716-1a72-4498-a3e1-a62569e09bd4.png">

Our cache setup:

![Screen Shot 2022-05-04 at 12 28 15 PM](https://user-images.githubusercontent.com/4844840/166811563-db42f5ff-bf2c-4e3c-a800-260e68cc2d66.png)

Any insight on:

1. What causes cache to stay in a `loading `state?
2. The cause of the aforementioned error?

**Comment by arthurfiorette** [comment]
It seems that the code is being tree-shaked and its generating two different storage symbols...

https://github.com/arthurfiorette/axios-cache-interceptor/blob/2571138215a7160217f48d8524a1debcd1b2582a/src/storage/build.ts#L11

Can you test disabling minification and seeing if the issue persists?

**Comment by KevinFreistroffer** [comment]
Sure, how can I do that, and in which folder(s) and what file(s)?

**Comment by arthurfiorette** [comment]
I meant with your frontend code. You're probably using webpack or vite to bundle your frontend.

**Comment by KevinFreistroffer** [comment]
We're using Create React App. This is in development on localhost, pre build.

**Comment by arthurfiorette** [comment]
No problem. Disabling minification on your dev setup still throws this error? If so, even if you use the default storage?

**Comment by arthurfiorette** [comment]
I'll change the symbol usage to a private property, this will resolve the `Use buildStorage() function` error, enabling you to debug your issue.

**Comment by arthurfiorette** [comment]
[dist.zip](https://github.com/arthurfiorette/axios-cache-interceptor/files/8626960/dist.zip)

I zipped the updated dist and dev folder so that you won't have to wait I release the next version...

You can unzip these two folders inside your `node-modules/axios-cache-interceptor` folder. Then you'll be able to debug your issue normally.

**Comment by arthurfiorette** [comment]
Sorry, misclick

**Comment by KevinFreistroffer** [comment]
Thank you! We'll give it a shot.

**Comment by KevinFreistroffer** [comment]
Same error. I replaced the dev & dist folders, and restarted the application.

**Comment by arthurfiorette** [comment]
Create react app saves some cache inside your node modules. I do not know where it is, but you can delete all your node_modules and dist folders, install I again, replace those axios-cache-interceptor folders and try starting your server. 

You can test by putting a console.log here in your code, that way you know if it read the updated file.

**Comment by arthurfiorette** [comment]
Did you manage to make it work?

**Comment by KevinFreistroffer** [comment]
Yes, that fixed the debugging working, however Jest is unable to import them. We're instead trying to use session storage.

With this in mind, what is the cause of a caching state staying in a `loading` state? We see the request was successful. Any ideas on how we can debug this?

Thank you for the help.
