### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by arch1v1st** [arthurfiorette/axios-cache-interceptor#239]
Hello,

Great module!  After exploring all other Axios caching options, this came out on top for its speed and flexibility of configuration. :)

While getting into the nitty gritty of our implementation needs, I stumbled across an apparent typo in this documentation:

https://axios-cache-interceptor.js.org/#/pages/request-id?id=custom-generator

I believe ```generateKey: keyGenerator``` should rather be ```generateKey: buildKeyGenerator```.

**Comment by arthurfiorette** [comment]
Thank you! I've just read another pages and seems that there are a lot of typos in it too... 😁😁

**Comment by arthurfiorette** [comment]
Hey, it's now live at https://axios-cache-interceptor.js.org/#/pages/request-id?id=custom-generator
