### ISSUE TITLE
bug: Invalidating Cache not working

### ISSUE THREAD

**Issue by ParsonsProjects** [arthurfiorette/axios-cache-interceptor#279]
### Describe the bug

When applying the logic to invalidate a cache neither approach is working, using the dev code to debug it looks like the `Response not cached but storage is not loading` is always being triggered. 

It seems the logic `cache.state !== 'loading'` should be `cache.state === 'loading'` otherwise every request that is not a get request sees this branch as true. 

As I do not know this library inside out I might be wrong, any help is appreciated. Thanks

### To Reproduce

Follow the example outlined here to invalidate a cache [invalidating-cache](https://axios-cache-interceptor.js.org/#/pages/invalidating-cache)

### Expected behavior

The cache is invalidated correctly.

### Additional context

- Axios: `0.26.0`
- Axios Cache Interceptor: `0.10.5`
- What storage is being used: `Web Storage`
- Node Version: `v14.19.0`
- Browser (if applicable): `Chrome Version 102.0.5005.115`

**Comment by ParsonsProjects** [comment]
Update: I tried that change and now it invalidates the cache but it is now caching every method 😵‍💫

**Comment by arthurfiorette** [comment]
Hey, can you give us a code example, so I'll try to find/fix the same bug as you?

**Comment by ParsonsProjects** [comment]
@arthurfiorette Sure, here is a simple demo, the Get button caching a get request, the Add button triggers a Post request which should remove the previous get request but the cache is still in the session storage.

**Comment by arthurfiorette** [comment]
Hey @ParsonsProjects, sorry for the response delay...

What you said makes total sense. Before, the `cache.update` was only being executed if the request could be cached. In your case, the [`methods`](https://axios-cache-interceptor.js.org/#/pages/per-request-configuration?id=cachemethods) property did not contain `post` (that's why it wasn't working for u).

A quick fix for now is to use it like this:

```ts

axios.post('url', data', {
  cache: {
    // Allows the update key to be executed
    methods: [...axios.defaults.cache.methods, 'post'],
    
    // Ignores the current cache, if available. Simple fix to
    // avoid caching (as the above property allows it)
    override: true,
    
    ...
  }
});
```

I'll set up some tests and release a patch for it ASAP.

Also, thanks for your codesandbox example, it helped a lot!

**Comment by arthurfiorette** [comment]
I've created a unit test. Can you confirm-me that this unit really represents your issue?

https://github.com/arthurfiorette/axios-cache-interceptor/blob/6d0cb72aa2e20bdb78e0d6d51564d56ab0498c04/test/util/update-cache.test.ts#L124-L142

**Comment by ParsonsProjects** [comment]
@arthurfiorette thank you for taking a look. 

Yes that looks correct, to be able to clear the cache without the update request being cached. 

I did think of another around this, of calling `await axios.storage.remove('list-posts');` after the POST request. Just means extra steps outside of the update request parameters.
