### ISSUE TITLE
bug: typescript tsc build throwing complier error

### ISSUE THREAD

**Issue by himasimplisafe** [arthurfiorette/axios-cache-interceptor#296]
### Describe the bug

tsc (typescript compiler) is throwing below error
#16 5.784 node_modules/axios-cache-interceptor/dist/storage/web-api.d.ts(21,50): error TS2304: Cannot find name 'Storage'.

### Additional context

- Axios: `^0.26.0`
- Axios Cache Interceptor: `^0.10.6`
- What storage is being used: `Redis`
- Node Version: `v14.8.1`
- typescript : v4.7.4

**Comment by himasimplisafe** [comment]
<img width="791" alt="Screen Shot 2022-07-14 at 12 30 44 PM" src="https://user-images.githubusercontent.com/24592500/179031862-fe9d68c5-322a-4953-9579-a21ffc18f2cc.png">

**Comment by himasimplisafe** [comment]
Looks like in this `https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/src/storage/types.ts`, you do not have type `Storage` to resolve compiler error, i have changed to `any` for `storage` like 
`export declare function buildWebStorage(storage: any, prefix?: string): import("./types").AxiosStorage;`

Once you have created `Storage` type, you can use it, meanwhile changing to `any` will unblock users using this npm package perhaps?

**Comment by arthurfiorette** [comment]
Storage is a built in web/node type. You can fix this issue by installing @types/node.

**Comment by himasimplisafe** [comment]
Oh good to know, thank you

**Comment by arthurfiorette** [comment]
Hmm, can you build a small reproducible example? Seems that your issue is because of your node environment... 

This just a type error? Or it actually crashes at runtime?

**Comment by himasimplisafe** [comment]
It is failing at compile time - for command `tsc`, i am not even using `buildWebStorage`

I have versions like below
Axios: ^0.26.0
Axios Cache Interceptor: ^0.10.6
What storage is being used: Redis
Node Version: v14.8.1
typescript : v4.7.4

my code look like this

`const redisStorage = buildStorage({
  async find(key) {
    const result = await redis.get(`axios-cache:${key}`);
    return JSON.parse(result);
  },

  async set(key, value) {
    await redis.set(`axios-cache:${key}`, JSON.stringify(value));
  },

  async remove(key) {
    await redis.del(`axios-cache:${key}`);
  },
});`

**Comment by himasimplisafe** [comment]
@arthurfiorette any update here?

**Comment by arthurfiorette** [comment]
If I define a `Storage` interface, this package can break any other users who use this library and also use storage separately. I would be setting a baseline for any other use of '`Storage`'. Since this is supposed to be a built-in javascript type, I won't add it to my own library to replace it.

**Comment by arthurfiorette** [comment]
Did you manage to figure why the `Storage` type isn't globally available for you? If not, you could tru declare it globally yourself.

```ts
declare global {
  interface Storage {}
}
```

**Comment by himasimplisafe** [comment]
yes, i needed to add DOM to the `"lib": ["es2020"],`
