### ISSUE TITLE
bug: Can't import form non EcmaScript module

### ISSUE THREAD

**Issue by Snotax** [arthurfiorette/axios-cache-interceptor#323]
### Describe the bug

Getting this error while starting the project: 

../app/node_modules/axios-cache-interceptor/dist/index.mjs
Can't import the named export 'deferred' from non EcmaScript module (only default export is available)

### Additional context

"axios": "^0.27.2",
"axios-cache-interceptor": "^0.10.7",
node: 14.7.0

Do you think there is a fix for this problem ?

**Comment by arthurfiorette** [comment]
Seems that the problem is your environment setup. Could you provide a reproductive example?

**Comment by arthurfiorette** [comment]
Hey, @Snotax.

Seems that the problem is your environment setup. Could you provide a reproductive example? Like a Codepen url.

**Comment by Snotax** [comment]
@arthurfiorette  I found a solution today: 
You have to enable .mjs files in the craco.config.js.

```
module.exports = {
  webpack: {
    configure: (webpackConfig) => {
      webpackConfig.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
      });
      return webpackConfig;
    },
    
    plugins: [
      // Inject the "__DEV__" global variable.
      new webpack.DefinePlugin({
        __DEV__: process.env.NODE_ENV !== "production",
      })
    ],
  },
};
```
