### ISSUE TITLE
Type error: Cannot find name 'Storage'

### ISSUE THREAD

**Issue by cainthebest** [arthurfiorette/axios-cache-interceptor#329]
### Describe the bug
A type error emitted from tsc when building

```bash
node_modules/axios-cache-interceptor/dist/storage/web-api.d.ts:21:50 - error TS2304: Cannot find name 'Storage'.

21 export declare function buildWebStorage(storage: Storage, prefix?: string): import("./types").AxiosStorage;        
                                                    ~~~~~~~


Found 1 error in node_modules/axios-cache-interceptor/dist/storage/web-api.d.ts:21
```

it seems that the type `Storage` is not defined on the line below
https://github.com/arthurfiorette/axios-cache-interceptor/blob/156198e19ff328d8d5ddbf7fe907376b3ea4fc24/src/storage/web-api.ts#L24

### To Reproduce
build a package with it as a dep

### Expected behavior
Builds with no type errors

### Additional context

- Axios: `v0.27.2`
- Axios Cache Interceptor: `v0.10.7`
- Node Version: `v16.16.0`

**Comment by cainthebest** [comment]
Ignore me made a whoops by forgetting to include `DOM` in the lib param within tsconfig

**Comment by arthurfiorette** [comment]
Same as #296 :) Good catch!

**Comment by giorgiosironi** [comment]
Started running into this problem when [upgrading an unrelated library](https://github.com/sciety/sciety/pull/3545).

I do not understand why I can compile correctly `axios-cache-interceptor`'s main branch, even if it [does not include `DOM` or any explicit `lib` setting](https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/tsconfig.json). Perhaps it's implied by some other setting in there.
