### ISSUE TITLE
Can't import the named export 

### ISSUE THREAD

**Issue by amir-beheshty** [arthurfiorette/axios-cache-interceptor#354]
```
./node_modules/axios-cache-interceptor/dist/index.mjs
Can't import the named export 'deferred' from non EcmaScript module (only default export is available)
```
I don't have access to webpack's config file and ejecting it is not ideal. I think this is better solved in `axios-cache-interceptor` export file.

**Comment by arthurfiorette** [comment]
Does your package.json setups your nodejs code as an [ecmascript](https://nodejs.org/api/esm.html) one?

**Comment by arthurfiorette** [comment]
Closes as stale.
