### ISSUE TITLE
bug: memory storage uses the same instances across requests

### ISSUE THREAD

**Issue by CatchABus** [arthurfiorette/axios-cache-interceptor#377]
### Describe the bug
In-memory cache seems to cache objects and arrays as instances.
This may result into issues as one may assign stuff to instances returned by `response.data`.

### To Reproduce
One possible way to see how this could go wrong would be to define properties to `response.data` instance using `Object.defineProperty`.
Next time request is performed, `Object.defineProperty` will be called anew resulting in error as property will already be defined.

### Expected behavior
I would expect in-memory cache to store JSON strings instead. Then, when request is performed anew, a JSON.parse will decode string and populate `response.data`.

### Additional context

- Axios: `v0.27.2`
- Axios Cache Interceptor: `latest`
- What storage is being used: `In-memory Storage`
- Node Version: `v18.0.1`

**Comment by arthurfiorette** [comment]
This is not a bug because we have a flag to solve it. 

https://github.com/arthurfiorette/axios-cache-interceptor/blob/d500835c5ac3bc7ad4615da4788d0c39408f61c4/src/storage/memory.ts#L36

You need to create a custom memory storage with clone data as true.

You can reopen if it did not solve your issue.

**Comment by CatchABus** [comment]
> This is not a bug because we have a flag to solve it.
> 
> https://github.com/arthurfiorette/axios-cache-interceptor/blob/d500835c5ac3bc7ad4615da4788d0c39408f61c4/src/storage/memory.ts#L36
> 
> You need to create a custom memory storage with clone data as true.
> 
> You can reopen if it did not solve your issue.

Oh, this must be a new addition because I couldn't find it in the docs.
Thank you very much, this solved all problems I encountered. Memory storage gets quite troublesome without it.
