### ISSUE TITLE
[localStorage] SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by CatchABus** [arthurfiorette/axios-cache-interceptor#424]
### Describe the bug

In firefox, there are times when my local storage hits the limit.
This results in `DOMException: The quota has been exceeded.` error which is caught by cache-interceptor plugin.

When it's caught, plugin tries to free some space: https://github.com/arthurfiorette/axios-cache-interceptor/blob/f4f4be1cd2f63f2a31544e2ed72a26f8e30f2a3e/src/storage/web-api.ts#L45

The issue here is I might have other values stored in `localStorage` and cache-interceptor will attempt to meddle with them at the location I mentioned above.
If I store a value like `localStorage.set("mytheme", "dark");`, plugin will attempt to call `JSON.parse` with "dark" as an argument.
This results in `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

This may not occur if I set a prefix for my storage.
My suggestion to avoiding this is to perhaps add a default prefix value to plugin.

```js
- export function buildWebStorage(storage: Storage, prefix = '')
+ export function buildWebStorage(storage: Storage, prefix = 'axios-cache')
```

### To Reproduce
Make sure localStorage gets full.

### Expected behavior
Should not throw errors.

**Comment by arthurfiorette** [comment]
Shure, I let this without prefixes to avoid breaking changes.

But we've been working on v1.0 and it totally fits. Would you mind doing a PR?
