### ISSUE TITLE
Basic Authorization

### ISSUE THREAD

**Issue by danilowm** [arthurfiorette/axios-cache-interceptor#433]
Hello, 
Congrats for a excellent job! 

I need to pass Authorization Basic in Header, but, when I pass the Headers, cache dont work
```
const api = setupCache(
  axios.create({
    baseURL: process.env.DEV
      ? "https://URL.com.br/wp-json"
      : "https://URL.com.br/wp-json",
    headers: {
      Authorization: `Basic ${window.btoa("pass")}`,
    },
  }),
  {
    storage: buildWebStorage(localStorage, "axios-cache:"),
    debug: console.log,
  }
);
```

If I remove the Headers, cache work

I do something wrong?

Thank you

**Comment by arthurfiorette** [comment]
_Fala mano, tu é BR hahaha. Vou manter esse tópico em ingles para facilitar outros leitores._

Actually, we do not have any constraint regarding the `Authorization` header. Are you sure that the response isn't returning different headers for authorized and not authorized requests?

You can, in details, understand why your request is not getting cached by enabling [debug mode](https://axios-cache-interceptor.js.org/guide/debugging).

If you still need help, you can write here both response headers and I'll help you.

**Comment by danilowm** [comment]
_sim, BR kkkkkkk inglês de Open English é foda kkkkkk_

It probably returned different headers that's why it didn't work

I solved my case doing this:
- removed Headers for the `Axios.create`
- added Header only when I need to Authorization API (without cache)

**Comment by arthurfiorette** [comment]
Well, I guess this isn't the optimal solution, as you are probably ignoring cache for most of your requests (authorized ones).
If you have control of the api, you could change it in their side, if not, you probably want to override the header interceptor to ignore the specific header that any authorized response are being used to avoid cache.

**Comment by arthurfiorette** [comment]
Closed as resolved.
