### ISSUE TITLE
the cache not working when use it with axios.create()

### ISSUE THREAD

**Issue by JordenLCH** [arthurfiorette/axios-cache-interceptor#441]
### Describe the bug

I need to use Axios with rate limit option, the module that I currently using is `axios-rate-limit`, it require us to use `axios.create()` when initiating the Axios module

### To Reproduce
1. open `https://axios.requestcatcher.com` in browser to view the requests
2. run the code below
```
const axios = setupCache(Axios);
const axiosRL = axios.create()

// still call 10 times
for (let i = 0; i < 10; i++) {
  axiosRL.get("https://axios.requestcatcher.com/", {});
}

// works fine
for (let i = 0; i < 10; i++) {
  axios.get("https://axios.requestcatcher.com/", {});
}
```

### Expected behavior
only call 1 time when we use the axios.create()

### Additional context

- Axios: `E.g: v1.2.2`
- Axios Cache Interceptor: `E.g: v1.0.0`
- What storage is being used: `Default`
- Node Version: `E.g: v16.17.0`
- Browser (if applicable): `none`

**Comment by arthurfiorette** [comment]
You are defining the interceptor on the global instance: `setupCache(Axios)`. It won't work on other instances, you need to call `setupCache()` on them too.

**Comment by JordenLCH** [comment]
It works, thanks for your clarification

**Comment by cborchert** [comment]
I have the same issue (and solution) as @Sid-Turner-Ellis

**Comment by arthurfiorette** [comment]
@cborchert Where's the issue? Using `headerInterpreter: () => 10000` is like disabling header interpreter and using ttl of 10000. Previously wasn't caching because your server sent headers told us to not do so.

**Comment by cborchert** [comment]
OK I think I understand, but just to confirm: 

If the API I'm hitting returns Cache-Control headers like no-cache, etc. axios-cache-interpretor will respect those headers *regardless of the value of the ttl value in the config* unless the cache.interpretHeader is set to false?

I'm seeing that this is specified in the documentation https://axios-cache-interceptor.js.org/config#headerinterpreter, but I guess I didn't understand read as thoroughly as I should have and the behavior seemed unintuitive. 

It might be worthwhile to add an example with a specific ttl in the getting started section of the documentation. 

Thanks for your help!
