### ISSUE TITLE
Axios default interceptors are not working

### ISSUE THREAD

**Issue by abhinavchawla13** [arthurfiorette/axios-cache-interceptor#449]
### Describe the bug
I have a react app using axios package which has two interceptors (one response, one request) like in the snippet below. 
After I wrap it around the `setupCache` wrapper, the access tokens are not added. Can someone help me with what's going wrong?

### To Reproduce
```
const instance = Axios.create({
    baseURL,
});

// Add a request interceptor
instance.interceptors.request.use(async (config: AxiosRequestConfig) => {
    config.headers.Authorization = await getIdToken();
    return config;
});

instance.interceptors.response.use(
    (response) => {
        if (response.headers['x-backend-version']) {
            handleVersion(response.headers['x-backend-version']);
        }
    },
    (error) =>
        Promise.reject(
            (error && error.response && error.response.data) || error
        )
);

const axios = setupCache(instance);
```

### Expected behavior
Have headers being intercepted properly

### Additional context

- Axios: `v0.26.1`
- Axios Cache Interceptor: `v1.0.0`
- What storage is being used: `Default`
- Browser (if applicable): `Chrome 108`

#### Debug log
```
{
    "id": "2124243715",
    "msg": "Sending request, waiting for response",
    "data": {
        "overrideCache": false,
        "state": "empty"
    }
}
```

**Comment by arthurfiorette** [comment]
Axios interceptors are registered in a different order. Take a look at this examples:

```ts
const axios = Axios.create();

axios.interceptors.request.use((a) => {
  console.log(1);
  return a;
});
axios.interceptors.response.use((a) => {
  console.log(2);
  return a;
});

// setupCache registers internal interceptors
setupCache(axios);

axios.interceptors.request.use((a) => {
  console.log(3);
  return a;
});
axios.interceptors.response.use((a) => {
  console.log(4);
  return a;
});
```

which prints `3`, `1`, `2` and `4`.

I made an image _(in ms paint)_ representing the execution order because its simpler than me writing it.

![image](https://user-images.githubusercontent.com/47537704/210458038-52515ebd-15a1-42f4-ba28-6c014b0a96cb.png)

I'll try to document it, but the correct way is to **apply the response interceptor before the `setupCache()` call and the request interceptor after it**.

**Comment by abhinavchawla13** [comment]
Thanks, @arthurfiorette for the explanation. I had to add the response interceptor after the `setupCache` only. I'll test it out a bit more, but thanks. We can close the issue, the main learning being that the `setupCache` doesn't need to come at the very end as I had before.

**Comment by arthurfiorette** [comment]
Just commenting here to say that this has been documented.
http://localhost:1227/guide/interceptors
