### ISSUE TITLE
bug: don't working vuejs 3

### ISSUE THREAD

**Issue by norby004** [arthurfiorette/axios-cache-interceptor#456]
### Describe the bug

Does not working vuejs 3 and axios.
Please help me!

### Additional context

- Axios: v1.2.2
- Axios Cache Interceptor: v1.0.0
- What storage is being used: Web Storage
- Node Version: v14.21.1

`const axiosClient = setupCache(axios.create({
	baseURL: import.meta.env.VITE_API_URL,
}));`

Run 2x:
`apiCall({method: 'get', url: '/example'});`

`axiosClient.interceptors.response.use(function (response) {
	console.log(response.cached);
	return response;
});`

The console just returns false.

**Comment by arthurfiorette** [comment]
Can you share an example that I could test it myself?

**Comment by norby004** [comment]
> Can you share an example that I could test it myself?

Hm.

It's working:
https://codesandbox.io/s/polished-wind-itzd7y?file=/src/App.vue

But then it is possible because of vue-router problem?

**Comment by norby004** [comment]
Sorry my mistake.

The API Cache-Control header wrong settings.
