### ISSUE TITLE
Is it possible to use cache with post method?

### ISSUE THREAD

**Issue by bytrix** [arthurfiorette/axios-cache-interceptor#459]
I'm looking for a cache mechanism for http request in my frontend project these days and I found Axios Cache Interceptor fit my project, but the problem I have now is that most of the APIs in my project is using `post` method to fetch data instead of `get`.

so, when I use axios.post, the cache doesn't work:
```javascript
const req1 = await axios.post('/api-1', body);
const req2 = await axios.post('/api-2', body);
console.log(req1.cached) // false
console.log(req2.cached) // false
```
how can I make cache work using `axios.post`? please help!

**Comment by arthurfiorette** [comment]
https://axios-cache-interceptor.js.org/config/request-specifics#cache-methods

**Comment by arthurfiorette** [comment]
Feel free to reopen this issue.
