### ISSUE TITLE
bug: Property cacheTakeover results into CORS policy errors

### ISSUE THREAD

**Issue by CatchABus** [arthurfiorette/axios-cache-interceptor#471]
### Describe the bug

It seems that leaving property `cacheTakeover` to default value (true) results in CORS policy errors due to no-cache headers being set. This block seems to be the culprit: https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/src/interceptors/request.ts#L39

Preflight requests end up with the following:
```
Request header field expires is not allowed by Access-Control-Allow-Headers in preflight response.
Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
```

### To Reproduce

I'm doing request to a REST API which browser performs cors preflight requests for.

### Expected behavior

Should not throw CORS policy errors.

### Additional context

- Axios: `1.2.3`
- Axios Cache Interceptor: `1.0.0`

I wonder if this property should be false by default.

**Comment by arthurfiorette** [comment]
This is intended behavior. You browser is just doing what your backend told to do so.

Expires and Pragma are cache compliant headers that has open wide usage. You'll have to add them in your backend cors config or diasble cache takeover.

**Comment by CatchABus** [comment]
> This is intended behavior. You browser is just doing what your backend told to do so.
> 
> Expires and Pragma are cache compliant headers that has open wide usage. You'll have to add them in your backend cors config or diasble cache takeover.

I see your point. Regarding `pragma`, perhaps it should be removed soon as it's deprecated.
```
Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.
```

Thanks for quick response.

**Comment by arthurfiorette** [comment]
Regarding Pragma usage, it is required for iOS Safari to work.
https://bugs.webkit.org/show_bug.cgi?id=170714

**Comment by dsuttonpreece** [comment]
Is it possible to remove these headers as they're causing this error on a backend I don't have control over?

**Comment by arthurfiorette** [comment]
@dsuttonpreece
https://axios-cache-interceptor.js.org/config/request-specifics#cache-cachetakeover
`cacheTakeover: false`
