### ISSUE TITLE
Etag handling

### ISSUE THREAD

**Issue by Cactusbone** [ArthurFiorette/axios-cache-interceptor#49]
I've stumbled on this lib from [Any plans on ETag support?](https://github.com/RasCarlito/axios-cache-adapter/issues/174)
but I can't find any reference to `If-None-Match` in the source.

Is there any plans for this ? (I'll try to provide a PR if I can make it work quickly :) )

**Comment by ArthurFiorette** [comment]
Hi!
I was about to implement a support for this, I even commented on this subject.
The strange thing is that I ended up not needing this support anymore and I forgot that I was going to implement it, hahaha.

Now I have to keep my words and do it. I got here so quickly I don't know if you've made any progress yet, but I'll try to do it now and keep in touch here.

**Comment by ArthurFiorette** [comment]
What about adding [`If-Modified-Since`](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/If-Modified-Since) support together?

**Comment by Cactusbone** [comment]
yep, should be close enough for that :)

I've just noticed you're not reading `age` too in header interpreter (ttl = max-age -age) :)

**Comment by ArthurFiorette** [comment]
> yep, should be close enough for that :)
> 
> I've just noticed you're not reading `age` too in header interpreter (ttl = max-age -age) :)
> 
> I'm not used to typescript so you may be faster than me imprementing it though :)

You mean [`Age`](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/Age)?

**Comment by Cactusbone** [comment]
> 
> 
> > yep, should be close enough for that :)
> > I've just noticed you're not reading `age` too in header interpreter (ttl = max-age -age) :)
> > I'm not used to typescript so you may be faster than me imprementing it though :)
> 
> You mean [`Age`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Age)?

Yes :)

**Comment by Cactusbone** [comment]
> One question, does axios automatically sends `If-None-Match` if the previous request returned an `ETag`?

Nope, since axios has no cache to know the previous request headers :)

**Comment by Cactusbone** [comment]
I'm pushing my current branch (tests not passing yet), I'll get back on it tomorrow :) 

(and this is not too far from handling `stale-while-revalidate` in cache-control too)

**Comment by ArthurFiorette** [comment]
I made the changes I think needed and pushed it to an [`header-improvements`](/ArthurFiorette/axios-cache-interceptor/tree/feat/header-improvements) branch, take a look.

I saw your changes, I also saw that you created a new type of StorageValue called stale (me too). But there are some bugs and some things I prefer to keep, like the storage doesn't have to validate that the cache is valid, keep the headers in lowercase and so on.

The logic I'm current using is:

### Initial Context

1. Request is made (with or without etag caching enabled). `State: empty -> loading`

2. Reply arrives normally, is cached, returned, and nothing else. `State: loading -> cached`

### Without **ETag**

3. Another request is made with etag disabled. `State: cached`

4. It was already in the cache and is returned to the previous one. `State: remain cached`

### With **ETag**

3. Another request is made with etag activated. `State: cached -> fallback`

4. Response arrives with `200 OK`. `State: fallback -> cached` _(Fallback deleted and cache kept with new values)_ 

4. Response arrives with `304 Not Modified`. `State: fallback -> cached` _(Cache keeps old fallback values)_

I don't know how clear this is, but I think the source can clarify better, follow it through the [request interceptor and the response interceptor](https://github.com/ArthurFiorette/axios-cache-interceptor/tree/feat/header-improvements/src/interceptors). I'm still going to document these changes before merging. If you can help me testing and writing units for it, I would be grateful.

Tomorrow afternoon I should have more time for this project.

**Comment by Cactusbone** [comment]
I'm looking for a way to honor all caches headers at once, using max-age and then when expired, revalidating with etag, thus having the best of all worlds.

Usually etag is computed from body, and then compared to the `If-None-Match` header, so the only gain is network latency and potentially decoding. so if you stop using the cache and always wait for etag, there is an added network latency for each request (done in series, not in parallel), that was not there when using cache. (check [stale-while-revalidate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate)) what you named fallback is a "revalidate" state :)  

I'll look at your code again tomorrow and try again :)   
I do agree to keep headers lowercased since axios does that already :)

**Comment by ArthurFiorette** [comment]
> I'm looking for a way to honor all caches headers at once, using max-age and then when expired, revalidating with etag, thus having the best of all worlds.

You should be supposed to achieve that with `interpretHeaders`, which is in charge of interpreting headers that only return a timestamp. `Etag`, `If-Modified-Since` or the like, should be implemented with another option, as they interfere with the logic beyond setting a time.

> so if you stop using the cache and always wait for etag, there is an added network latency for each request (done in series, not in parallel), that was not there when using cache. (check stale-while-revalidate) 

What do you mean to always wait for an `ETag`? A new etag is only sent if the body has changed (like you said), but that means fresher content, otherwise is a 304 with empty body. And the latency gained by this tiny response is necessary to know if it has new content or not. What would be the other method of knowing if you have new content (before it expires) that doesn't have a latency greater than the cache?

The small latency lost is what would be fixed by implementing stale-while-revalidate? The only change I see would be a new option, (similar or inside `interpretHeader` functionality), that if the cache is within the stale-while-revalidate period, another asynchronous request would be made so that the next requests use the fresh content.

> what you named fallback is a "revalidate" state :)

Thanks, it makes perfect sense! I can rarely remember a good name without spending more time looking up the name than implementing the thing.

**Comment by Cactusbone** [comment]
yep, a new ETag is sent only with fresh content, i meant a revalidation :p  

Etag and If-Modified-Since are meant to use for revalidation, and should not interfere with the time caching from interpretHeaders (max-age), normally a cache (for example varnish-cache) caches stuff, wait until it expires, and then revalidate content. When you revalidate (using an etag for example), if you receive a 304, that means the data is still current but you may also receive a new max-age (and potentially age), which should be used until the next validation (yup, I did that wrong in my branch ;) )

this image explains it very well https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching/http_staleness.png (from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching))

**Comment by ArthurFiorette** [comment]
I'm back!

> Etag and If-Modified-Since are meant to use for revalidation, and should not interfere with the time caching from interpretHeaders (max-age), normally a cache (for example varnish-cache) caches stuff, wait until it expires, and then revalidate content. 

Yes, requesting every time and waiting for 304 every time doesn't seem like a good idea for an cache in-code. I think I needed more sleep :)

> There's no way to do it before it expires. Checking it at every request is the "must-revalidate" cache control.

I ended up implementing this as an undocumented feature, haha. And it should, along with the functionality to interpret headers. (It might have a better name like `cache control:`

> I've also set ttl to 1ms when "must-revalidate" is set, to allow revalidation (0ms would be better, but it involve more changes)

Maybe a new cache state would be a good idea, but not for now. Or ttl to 0 ms can be used to represent that situation...

I'm going to prefer your PR over mine and send some changes to it, let me just take a good look to what you've changed so far

**Comment by ArthurFiorette** [comment]
I think it's going to get a little disorganized with my and yours branches, I'll create a new branch and start over. I also invited you as a collaborator.

Some other changes:

- A "wrapper" to check if the cache is valid or not, removing this task from specific implementations.

**Comment by Cactusbone** [comment]
I think I can do a few things on my branch, tell me if you want me to proceed:

1. add a "revalidating" cache status instead of reusing the "loading" one 
2. split the "must-revalidate" changes to another branch.

Moving the isStale out of cache handling (which you proposed :) ) is indeed a good idea, it'll remove the stale cache status :) I can do that as a first commit in my branch, that'll make it more readable

**Comment by ArthurFiorette** [comment]
Moved must-revalidate and some refactors to another branch: https://github.com/ArthurFiorette/axios-cache-interceptor/pull/51

**Comment by ArthurFiorette** [comment]
I was trying a lot of things here and:

1. It's better to do static methods to help with storage, not treating it like a database, but treat it like storage. This means that removing the full ability to do checks and acting just like an API for a database can be more work, at the moment, than creating a few simple helper methods.
2. That said, I created the 'stale' state, which the storage (with the helper methods) would only give to a cached state with a header or anything else that would possibly need the value after it becomes stale. Which implies, further on, that the logic of saving an stale value can only be used if some property is saved in the cache (to be analyzed).

I still don't know if i'm going to create helpers methods to be called anywhere or make the get method protected, sort of a "gateway" to the data, and a public method built-in.

**Comment by ArthurFiorette** [comment]
See #53

It's still needing unit tests, but i'm tired today. In short:

There are 'etag' and 'modifiedSince' properties, to toggle his functionalities, available while making requests.

In the request interceptor, except for minor refactors, the only thing changed was the setRequestMethods, that applies `ETag` and/or `If-Modified-Since` headers when needed.

And in the response interceptor, if the response status is 304, and the actual loading state has the property `data`, the response.data is overrided to the old cache and the actual cache is updated.

And to complete the storage changes, i'm testing with the abstract way to handle invalidation, but i'm not sure if it is good enought.

**Comment by Cactusbone** [comment]
> 
> 
> See #53
> 
> It's still needing unit tests, but i'm tired today. In short:
> 
> There are 'etag' and 'modifiedSince' properties, to toggle his functionalities, available while making requests.
> 
> In the request interceptor, except for minor refactors, the only thing changed was the setRequestMethods, that applies `ETag` and/or `If-Modified-Since` headers when needed.
> 
> And in the response interceptor, if the response status is 304, and the actual loading state has the property `data`, the response.data is overrided to the old cache and the actual cache is updated.
> 
> And to complete the storage changes, i'm testing with the abstract way to handle invalidation, but i'm not sure if it is good enought.

You can pick tests from my branch, adding "etag:true" where needed :)

**Comment by Cactusbone** [comment]
fixed by #53
