### ISSUE TITLE
`staleIfError: true` should use the `stale-if-error` directive if present

### ISSUE THREAD

**Issue by arthurfiorette** [arthurfiorette/axios-cache-interceptor#506]
### Describe the bug

When using `staleIfError: true`, its time is resolved as forever, but if the cache-control header included a `stale-if-error` directive, that time should be used instead.

### To Reproduce

```ts
axios.get('url to a server that returns stale-if-error', {
  cache: { staleIfError: true }
});

// The cache will be stale forever.
```

### Expected behavior

When `staleIfError ` is true and the server returned the `stale-if-error` directive, it should behave exactly the same as `staleIfError: <ms in the stale-if-error directive>`

### Additional context

- Axios: `v1.3.1`
- Axios Cache Interceptor: `v1.0.1`

**Comment by arthurfiorette** [comment]
Anyone up to working on this?

**Comment by gmazoni** [comment]
Working on

**Comment by arthurfiorette** [comment]
Whoopsie, can you change the documentation where it was affected?

https://github.com/arthurfiorette/axios-cache-interceptor/blob/ee8b6b36a1629cae2b3a25b81a0ffde3754d5d62/src/cache/cache.ts#L167

and

https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/docs/src/config/request-specifics.md#cachestaleiferror
