### ISSUE TITLE
bug: memory not freed

### ISSUE THREAD

**Issue by panghaoyuan** [arthurfiorette/axios-cache-interceptor#513]
Does the library's ttl release memory after expiration, or just re-request after expiration. 
When I use the `nextjs` project, a large amount of memory will be accumulated and not released, and the cache will not be released after the TTL expires.

I looked at the node `heap dump` and there is a large cache of requests sitting in memory.

Does this library use real nodejs memory management. Libraries like `node-cache`.

**Comment by arthurfiorette** [comment]
Hey @panghaoyuan, the in memory default storage cleans itself in a lazy way, so there's no second task running to check whenever a cache can be evicted... This should only be a problem for long running processes, which seems to be your case.

You could try to use `buildStorage()` as a proxy to an `WeakMap` or maybe creating a `setInterval` to evict old entries...

**Comment by arthurfiorette** [comment]
We cannot use node-cache or similars because we must support every environment without environent dependent dependencies. Which is the case of `node-cache`.

**Comment by arthurfiorette** [comment]
If you solve this with your own custom storage, could you send us here so that I can put this solution on the documentation?

**Comment by arthurfiorette** [comment]
See 72de39c
