### ISSUE TITLE
Using Redis storage returns TypeError

### ISSUE THREAD

**Issue by Alexis90** [arthurfiorette/axios-cache-interceptor#515]
>>Setup:
```
const client = redis.createClient({
  url: "REDIS_URL",
});


const redisStorage = buildStorage({
  async find(key) {
    const result = await client.get(`axios-cache:${key}`);
    return JSON.parse(result);
  },

  async set(key, value) {
    await client.set(`axios-cache:${key}`, JSON.stringify(value), {
      PXAT: canStale(value) ? value.expiresAt : undefined,
    });
  },

  async remove(key) {
    await client.del(`axios-cache:${key}`);
  },
});

setupCache(axios, {
  storage: redisStorage,
});
```

>>test
```
app.get("/api/ditto", async (req, res) => {
  const result = await axios.get("https://pokeapi.co/api/v2/pokemon/ditto");
  res.status(200).json(result.data);
});
```

>>return Error:
```
TypeError: Cannot read properties of undefined (reading 'id')
    at o (D:\dev\axios-cache\node_modules\axios-cache-interceptor\dist\index.cjs:2:5515)
```

what did I do wrong to set it up? doesn't seem to be working with RedisStorage.

**Comment by Alexis90** [comment]
I tried with other API address, without setupCache just Axios it works. I breaks with axios cache

**Comment by arthurfiorette** [comment]
So this problem is because of redis storage or everywhere is throwing this error? If you remove the redis storage, it works?

**Comment by arthurfiorette** [comment]
Are you sure that no other interceptor are being plugged to axios? What the debug log prints out? The LOC in the stacktrace is in the onRejected response interceptor, probably the request itself also had an error...

**Comment by arthurfiorette** [comment]
Please follow the bug template: 

```
<!--
README

Make sure to enable development mode before creating a issue,
as it can print out the reason for a specific behavior.

https://axios-cache-interceptor.js.org/#/pages/development-mode
-->

### Describe the bug

<!--
A clear and concise description of what the bug is.
-->

### To Reproduce

<!--
Provide a clear and concise description of how to reproduce the bug.
It can be in form of a unit test, a snippet of code, a sequence of
steps or a minimum reproduction repository.

https://minimum-reproduction.wtf/
-->

### Expected behavior

<!--
A clear and concise description of what you expected to happen.
-->

### Additional context

- Axios: `E.g: v0.26.1`
- Axios Cache Interceptor: `E.g: v0.9.3`
- What storage is being used: `E.g: Web Storage`
- Node Version: `E.g: v16.9.1`
- Browser (if applicable): `E.g: Chrome 98`

<!--
Add any other context about the problem here.
-->
```

**Comment by Alexis90** [comment]
without Redis storage it works. 

`client.connect().then(()=>{console.log('connected!')})`

it prints out 'connected' 

if I do client.set(key, value) manually, I can see the result writes into my database. I suppose Redis storage has been correctly registered.

**Comment by arthurfiorette** [comment]
> client.connect().then(()=>{console.log('connected!')})

this is in the redis client, not related to axios cache interceptor.

**Comment by Alexis90** [comment]
![image](https://user-images.githubusercontent.com/101555353/223475785-80212ea2-0bb4-4159-89b8-5baa106f2c30.png)

**Comment by Alexis90** [comment]
> > client.connect().then(()=>{console.log('connected!')})
> 
> this is in the redis client, not related to axios cache interceptor.

no, just to say that the Redis storage normally has been correctly plugged in

**Comment by arthurfiorette** [comment]
I cannot help without an example to test it out myself.

You didn`t follow the bug template, providing your axios version, any additional context or even what is printed out by the debug mode.

Just a printscreen with the error you already mentioned above isn't enough. I don't even know what, with and how you created your axios instace...

**Comment by Alexis90** [comment]
> I cannot help without an example to test it out myself.
> 
> You didn`t follow the bug template, providing your axios version, any additional context or even what is printed out by the debug mode.
> 
> Just a printscreen with the error you already mentioned above isn't enough. I don't even know what, with and how you created your axios instace...

Sorry for that..
here is the code repo: https://github.com/Alexis90/axios-cache-debug.git
