### ISSUE TITLE
feat: Strictly typed example

### ISSUE THREAD

**Issue by awmcc90** [arthurfiorette/axios-cache-interceptor#516]
The library looks great and seems very efficient but there isn't any documentation about how to set it up in a strictly typed typescript environment. I don't know which generic args to pass to the `AxiosStatic` get function. And even when I manually cast axios to `AxiosCacheInstance` with the generic response type, data is always `any`.  

The example shown [here](https://axios-cache-interceptor.js.org/config/request-specifics#cache) will fail if setup in typescript.

**Comment by arthurfiorette** [comment]
The generics are exactly the ones that axios provides. No change were made, and even better, there are inline Ts Docs to all of them.

What error you were facing?

**Comment by arthurfiorette** [comment]
All generics, in case they need to be overridden manually, are documented by tsdoc. 

https://github.com/arthurfiorette/axios-cache-interceptor/blob/360ba57348dc6a8ab5a1af6d0a00249407de31e2/src/cache/axios.ts#L101-L245

If you find an non documented piece of code, feel free to reopen this issue!

**Comment by awmcc90** [comment]
Hey, sorry I didn't see your last message. This is my mistake. Axios is typically imported as `import axios from 'axios'` or `const axios = require('axios')`. So when I saw [this](https://axios-cache-interceptor.js.org/config/request-specifics#cache) example with lowercase axios I assumed it was the default export from the axios library and that this library was hooking the internal functionality to make that link work. I realize now that I'm just supposed to create an instance using `setupCache` and export that from a single place if I want to reuse it.
