### ISSUE TITLE
Follow RFC on `hydrate` and `stale-while-revalidate`.

### ISSUE THREAD

**Issue by arthurfiorette** [arthurfiorette/axios-cache-interceptor#519]
As long discussed on #514 and after reading more RFCs & looking up other languages client implementations. I have decided to follow [RFC 5861](https://datatracker.ietf.org/doc/html/rfc5861) instead of preferring a good DX and usability.

> RFC 3rd paragraph
> 
> If a cached response is served stale due to the presence of this extension, the cache SHOULD attempt to revalidate it while still serving stale responses (i.e., without blocking).

This way, the we should return the stale cache first, `revalidate` in the background and then call the `hydrate` callback.

- For requests with Stale While Revalidate, `axios()` should return the stale value and asynchronously  call `hydrate` later.
- For requests without Stale While Revalidate (a.k.a any request that is no longer valid), `hydrate` should be called with the stale value and axios() should only resolve when the network call resolves.

**I'm open to ideas and any opinions on how the `hydrate` behaviour switch depending on _SWR_ is not the best option.**

I created `hydrate` to specifically solve #469 related problems, not to follow the 1 person on the whole internet who has a backend with `stale-while-revalidate`, even because the #469 functionality is infinitely more noticeable for all end-users than `stale-while-revalidate`.

But this library must support both of these use cases.

**Comment by arthurfiorette** [comment]
@richardgarnier, what's your thoughts on this?

**Comment by richardgarnier** [comment]
It might be nice to separate hydrate in two callbacks:
- onStaleData: called whenever we have stale data available to return to the caller
- onRefreshedData: called whenever we finished refreshing a request in the background

In addition to that, if we change the implementation of stale-while-revalidate to not clear the stale data when we're no longer allowed to use it (by using a different cache state, `expired` or something), we could probably improve the consistency a little bit. OnStaleData would always be called as long as the cache is not fresh (or allowed to use the stale response), without being tied to stale-while-revalidate.

**Comment by richardgarnier** [comment]
Actually thinking about it more in depth (and considering stale-if-error) it might be best to only keep hydrate, but clarify what kind of data is returned.
We would need to implement it the following way:
```
Cache state
- fresh (using max-age)
- stale (using stale-while-revalidate / stale-if-error)
- expired (when we are no longer allowed to use it, but are keeping it to avoid UI flickering)

Hydrate
- Cache expired -> { data: Cache, state: expired }
- Cache stale + stale-if-error + Req error => { data: Cache, state: stale }
- Cache stale + stale-while-revalidate => { data: Server, state: refreshed }

Return
- Cache fresh => Cache
- Cache stale + stale-while-revalidate => Cache
- Cache stale + stale-if-error + Req error => Cache
- Otherwise => Server
```

**Comment by arthurfiorette** [comment]
After a little break, I thought a lot about this problem and messaged up some of the people who asked for `hydrate` and its real use case scenario.

Considerations:

- The purpose of `hydrate` is to have a little feedback with **EXPIRED** data when axios cannot return it and needs to request again before returning the response.

 - We **MUST** handle `stale-while-revalidate` normally, return stale data, request on the background _(Although I'm not sure how to do it inside an axios interceptor)_ and have fresh data for following requests. If a callback to be called after the fresh data is available is needed, may someone submit a PR and we'll discuss, but there were nothing specified about it in the RFC's I read.

So I decided to implement both, but keep each concept on its side and don't mix everything up.

_Open to discussions 😁_

**Comment by arthurfiorette** [comment]
Hey @richardgarnier.

After a little break, I thought a lot about this problem and messaged up some of the people who asked for `hydrate` and its real use case scenario.

Considerations:

- The purpose of `hydrate` is to have a little feedback with **EXPIRED** data when axios cannot return it and needs to request again before returning the response.

 - We **MUST** handle `stale-while-revalidate` normally, return stale data, request on the background _(Although I'm not sure how to do it inside an axios interceptor)_ and have fresh data for following requests. If a callback to be called after the fresh data is available is needed, may someone submit a PR and we'll discuss, but there were nothing specified about it in the RFC's I read.

So I decided to implement both, but keep each concept on its side and don't mix everything up.

_Open to discussions 😁_

**Comment by arthurfiorette** [comment]
As Axios architecture allows us, we cannot do a request in the background after returning cache data, as to do that, we would need to override the adapter. So, unless we ultimately create a new request by manually calling _`axios({...})`_, this cannot be done. The workaround is to request it normally and just start interpreting stale TTL in our header interpreter.

This may be a bit confusing, but its just internal things and, if so, I may write something on the docs furthermore. For now, I'll just link to this issue.

I'll release v1.1.0 in this current way and see what kind of feedback i'll receive.

Thanks :)

**Comment by Embraser01** [comment]
> So, unless we ultimately create a new request by manually calling axios({...}), this cannot be done

In that case, it could duplicate the request config and disable the cache to not indefinitely loop on itself and send the request in background. If it fails do nothing, otherwise, override the cache (concurrent requests may cause issues but checking on the freshest data should be enough).

For now we will go without "real" stale-while-revalidate cache as it's a low priority issue on our side, but having this would make the lib fully compliant with HTTP Cache.
Could there be an issue for this specific improvement ?

Anyway, thanks for the lib!
