### ISSUE TITLE
Return stale and schedule revalidation

### ISSUE THREAD

**Issue by kostia1st** [arthurfiorette/axios-cache-interceptor#525]
I have found no other way to ask a question other than posting it as an issue here. Please let me know if there a "questions" section somewhere which I have missed somehow.

Is there a way to return a stale cache result while scheduling an async refresh of the cache for _future_ requests?

- So, imagine we have request `#1`. There is no cache for it yet, so request is actually made, the result is written to cache, TTL 1 minute.
- In 2 minutes there's another request, `#2`. There is a stale cache, so I want that stale cache be used as a legit data for this request. However at the same time - wanna schedule a real request being made "in background", renewing the cache as the result.
- Than, there's a request `#3` made in 30 more seconds - we do already have a fresh cache, so just return it.

Is there an out-of-the-box way to setup this strategy? Or is there a simple know-how way to implement it using the current tool set?
Thanks in advance.

**Comment by kostia1st** [comment]
The ratio is, such an approach would give a predictable _instant_ performance for certain kind of requests. In my use-case, there are _lots_ of endpoints that could benefit big time from this kind of caching.

As I see it, this mechanic could be relatively easily implemented with the use of `hydrate`, creating a custom promise upfront, and resolving it in `hydrate` while allowing everything else to flow its way. Unfortunately, `hydrate` isn't available in the latest `1.0.1` version. Are there plans to make it to a release?

**Comment by arthurfiorette** [comment]
Hey, exactly what you need is going to be released on the next minor version (this weekend probably), #519 is what you're looking for.

**Comment by arthurfiorette** [comment]
Hey, exactly what you need is going to be released on the next minor version (this weekend probably), #519 is what you're looking for.

**Comment by arthurfiorette** [comment]
I'll close this issue as 519 is already open.
