### ISSUE TITLE
[Feat] change default "Memory Storage" to "CacheStorage"

### ISSUE THREAD

**Issue by cangSDARM** [arthurfiorette/axios-cache-interceptor#526]
https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage,

It's a nicer way to keep req and resp data for "cache" useages

**Comment by arthurfiorette** [comment]
Hey @cangSDARM, are you having problems with memory storage / web storages? What's the reason behind your request?

CacheStorage only works on the browser _(will need polyfill on node and will just be an memory abstraction)_ and only accepts [`fetch`'s response](https://developer.mozilla.org/en-US/docs/Web/API/Cache/put#parameters) values. Axios Cache Interceptor needs to store a little bit more info to cache correctly.

If you really want to use CacheStorage for some reason, I guess you could hack something together with `buildStorage`, but there's no need for it and will be worse.
