### ISSUE TITLE
improvement: Clear full storage

### ISSUE THREAD

**Issue by fredymorales** [arthurfiorette/axios-cache-interceptor#528]
For testing purposes (and maybe another usage) I'd like to delete the full storage.

I think exposing a storage.clear() similar to `axios-cache-adapter` would be nice to have , if sounds good I can create a PR with a method similar to cleaner in: https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/src/storage/memory.ts#L74-L101

**Comment by arthurfiorette** [comment]
Yeah, open a PR and I'll review it :)
