### ISSUE TITLE
how to work with nuxtjs?

### ISSUE THREAD

**Issue by stephenliu1944** [arthurfiorette/axios-cache-interceptor#534]
I'm not sure how to work  with @nuxtjs/axios.
I try to code like this, but not work:
plugins/axios.js
```
import { setupCache } from 'axios-cache-interceptor';

export default ({ $axios, env, route }) => {
  if (process.server) {
    $axios = setupCache($axios);
  }
  ...
}
```

please give me a demo.

**Comment by arthurfiorette** [comment]
I have not used vuejs with nuxt enough to give you an production ready example neither have free time to simply write code for you :)

I can help you when you say what are your problem, cannot help with _"please give me a demo."_
