### ISSUE TITLE
native support with localforage & indexed db in browser

### ISSUE THREAD

**Issue by alexkrytsky** [arthurfiorette/axios-cache-interceptor#540]
as Axios-cache-adapter no longer supported in 1.* it would be nice to have a migration guide to this package. 
My current setup is Axios + Axios-cache-adapter + localforage + localforage-memoryStorageDriver. It's using indexeddb which is very convenient for persistence + this can support the "clear local cache" option reported in other threads.

**Comment by arthurfiorette** [comment]
Hey @alexkrytsky. Seems non trivial to axios-cache-interceptor natively support a specific library like `localForage`. But, it should be the most straightforward implementation ever. See https://axios-cache-interceptor.js.org/guide/storages#buildstorage for more help.
