### ISSUE TITLE
bug: code E401 command sh -c npx only-allow pnpm code E401

### ISSUE THREAD

**Issue by ale-grosselle** [arthurfiorette/axios-cache-interceptor#541]
### Describe the bug

Installing the latest (1.1.0) version and running `npm i` in my project, I got this error: 

![Screenshot 2023-05-24 at 13 00 38](https://github.com/arthurfiorette/axios-cache-interceptor/assets/6173088/eee15f1e-1602-4e54-a618-964868067c97)

This is related to the command: [`npx only-allow pnpm`](https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/package.json#L48)

Forcing to 1.0.0 it works as expected; indeed in this version the package.json is without that row

### To Reproduce

- Install the 1.1.0 version in a npm based project

### Additional context

- Axios: 1.x version

**Comment by arthurfiorette** [comment]
aa697999e4b44d90b7eef7081a65e7ed0799cd55
