### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by Snotax** [arthurfiorette/axios-cache-interceptor#544]
Did you drop the updates / support of the yarn package or did you just forget to push it there ?

We are currently using this package via yarn :D 

Thank you in advance :D

**Comment by arthurfiorette** [comment]
Hey, I thought 1.1.1 fixed the issue... What's the current problem for you?

**Comment by Snotax** [comment]
I'm sorry, I didn't quite write it correct. 

I have no problem with the library as it is. I just saw (https://yarnpkg.com/package/axios-cache-interceptor) still has v 1.0.1 and I wondered if you are still going to update the yarn package of the library in the future or only the npm one.

Sorry for the inconvenience.

**Comment by arthurfiorette** [comment]
Hey @Snotax, I was using yarn publish before v1.1 but now I migrated to pnpm. I have no plans to come back to use yarn. I have no idea on how to publish to the yarn registry manually. Would this be a problem for you?

**Comment by Snotax** [comment]
@arthurfiorette Hmm yes... this would be a problem for us. We're using react-native with a yarn monorepository. We would have to migrate to another caching solution.

**Comment by Snotax** [comment]
@arthurfiorette  Thank you for your insights. We will try to configure it this way. I will hit you up again if anything failes :D

**Comment by Embraser01** [comment]
Casually passing by: Yarn registry [is actually](https://yarnpkg.com/getting-started/qa#queries-to-registryyarnpkgcom-return-a-404500-is-it-down) just a CNAME on the npm registry, so there shouldn't be any difference with npm.

**Comment by arthurfiorette** [comment]
Well, now I'm confused... I do not have any idea on why there's only up to 1.0.1 on yarn.

**Comment by Embraser01** [comment]
Oh right, on the website search, it doesn't show new versions. May be related to this https://github.com/yarnpkg/berry/issues/5451 issue (TLDR: Yarn uses an algolia index that seems not up to date)
