### ISSUE TITLE
Bug: Why is the method - POST unable to cache?

### ISSUE THREAD

**Issue by subhradeepnag** [arthurfiorette/axios-cache-interceptor#545]
```
const Axios = require('axios')
const { setupCache } = require('axios-cache-interceptor')

const cacheTTL = 15 * 1000 // 15 seconds

const axiosInstance = Axios.create()
const cacheOptions = {
  interceptHeader: false,
  ttl: cacheTTL,
  methods: ['post']
}
const axios = setupCache(axiosInstance, cacheOptions)

async function callClient(options) {
  const response = await axios(options)
  return response
}

async function beforeCacheFunction(options) {
  const start = Date.now();
  const response1 = await callClient(options)
  const end = Date.now();
  const timeTaken = end - start;
  console.log(timeTaken) // in miliseconds
  console.log(response1.cached) //false
}

async function afterCacheFunction(options) {
  setTimeout(async () => {
    const start = Date.now();
    const response2 = await callClient(options)
    const end = Date.now();
    const timeTaken = end - start;
    console.log(timeTaken) // in miliseconds
    console.log(response2.cached) //false
  }, 2000)
}

beforeCacheFunction({
  url: 'https://reqres.in/api/users',
  data: {
    "name": "morpheus",
    "job": "leader"
  },
  method: 'POST'
})

afterCacheFunction({
  url: 'https://reqres.in/api/users',
  data: {
    "name": "morpheus",
    "job": "leader"
  },
  method: 'POST'
})
```

**Comment by arthurfiorette** [comment]
Have you used the debug logs?

**Comment by subhradeepnag** [comment]
I just saw cache-control is set to 'no-cache'. Is it because of that?

If yes, can we change that?

**Comment by arthurfiorette** [comment]
This are not debug logs.

https://axios-cache-interceptor.js.org/guide/debugging

**Comment by arthurfiorette** [comment]
That's your answer, the cache predicate rejects the response, that's why no caching are done. Your server is returning your post request with headers that explictly says to avoid cache. You can disable this behavior by turning off header interpreter.

**Comment by arthurfiorette** [comment]
> I just saw cache-control is set to 'no-cache'. Is it because of that?

Yes.

> If yes, can we change that?

That's a header sent from the server, you need to change it there if you have sufficient permissions to do so.

**Comment by subhradeepnag** [comment]
Sorry for reopening the thread again

> That's your answer, the cache predicate rejects the response, that's why no caching are done. Your server is returning your post request with headers that explictly says to avoid cache. You can disable this behavior by turning off header interpreter.

I've already set `interpretHeader: false`, Still it's not able to cache
