### ISSUE TITLE
bug: when a site have `dont cache` flag the request rejected

### ISSUE THREAD

**Issue by tupe12334** [arthurfiorette/axios-cache-interceptor#572]
### Describe the bug

I tried to use the interceptor on https://www.iposcoop.com/ipo/cytomed-therapeutics-pte-ltd/ but the site have a `dont cache` flag, instead of just don't use the cache, the lib rejects the request https://github.com/arthurfiorette/axios-cache-interceptor/blob/378574c05915aed929c40fda376649ed99b27c06/src/interceptors/response.ts#L157

### Expected behavior

The request should work properly but just ignore the cache

**Comment by arthurfiorette** [comment]
Hey @tupe12334, can you share the debug logs?

**Comment by arthurfiorette** [comment]
Hey @tupe12334. Tried to reproduce this issue again and it does not seems to be a bug. I'll close this issue for housekeep purposes. Feel free to reopen it if you need to!
