### ISSUE TITLE
requests deduplication not working

### ISSUE THREAD

**Issue by inikonorov** [arthurfiorette/axios-cache-interceptor#578]
hello! is requests deduplication supporting now? I try to send request in React hook which one is used in 4 components and I see all 4 requests in network

**Comment by arthurfiorette** [comment]
Yes it should be working... USe debug logs to understand why it is not caching.

**Comment by inikonorov** [comment]
If I will attach debug logs, will you explain me what's happening?

**Comment by inikonorov** [comment]
![image](https://github.com/arthurfiorette/axios-cache-interceptor/assets/30556799/fe204111-a9ae-48c6-b680-74fa8229ebae)
![image](https://github.com/arthurfiorette/axios-cache-interceptor/assets/30556799/376efcd8-a0e1-46f6-be2a-868ace892243)

**Comment by inikonorov** [comment]
Request is executed from hook in 2 different components on one page

**Comment by arthurfiorette** [comment]
Your responses are coming with explicitly headers saying to not cache the response, as its saying on `Cache header interpreted as 'dont cache'`. You can override this behavior with [`interpretHeader: false`](https://axios-cache-interceptor.js.org/config/request-specifics#cache-interpretheader).
