### ISSUE TITLE
usage of deprecated header: Pragma

### ISSUE THREAD

**Issue by bhallionOhbibi** [arthurfiorette/axios-cache-interceptor#579]
I'v been experimenting with this sweet library, and noticed the usage of the `Pragma` header.
While searching about it, I found out it is deprecated. I had to add it to my CORS allowed headers.
Perhaps you should consider removing it ?

Found on `axios-cache-interceptor` version "1.2.0"

Cheers

**Comment by arthurfiorette** [comment]
Pragma was added to ensure cross compatibility with older browsers. You can solve it the same way as #471.
