### ISSUE TITLE
Change all `type`s to `interface`s

### ISSUE THREAD

**Issue by arthurfiorette** [arthurfiorette/axios-cache-interceptor#606]
By migrating from `type` to `interface` everywhere it is possible, we enable our end-user to override/add/remove types and properties it want to change.

This improves our modularity in general.

Also, clarify how to extend axios-cache-interceptor types documentation:

```ts
declare module 'axios-cache-interceptor' {
  interface CacheRequestConfig<R = any, D = any> {
    myType: string;
  }
}
```

**Comment by denis-rossati** [comment]
Do you mind if I work on this one?

**Comment by arthurfiorette** [comment]
@denis-rossati its all yours
