### ISSUE TITLE
Avoid `RangeError: Maximum call stack size exceeded` on streams and other objects

### ISSUE THREAD

**Issue by arthurfiorette** [arthurfiorette/axios-cache-interceptor#608]
Currently, the ID is generated even when you use `cache: false`. The ID should only be created when cache is not false.

https://github.com/arthurfiorette/axios-cache-interceptor/blob/4f88736afc380813c469d888ca70966202bcd14f/src/interceptors/request.ts#L19

This line should be below the `config.cache === false`.

**Comment by joseiedo** [comment]
Hey, is it just the ID, or is there another known issue?

**Comment by arthurfiorette** [comment]
As far as I tested yes, but I'm not 100% sure.
