### ISSUE TITLE
Bug: Dev/Debug version is unresolved, unless manually pathed

### ISSUE THREAD

**Issue by xml** [arthurfiorette/axios-cache-interceptor#663]
### What happened?

Thank you for this tool! 

Per the debugging guide, I attempted to replace `import { setupCache } from 'axios-cache-interceptor'` with `import { setupCache } from 'axios-cache-interceptor/dev'`

This results immediately in errors both in my IDE and in the build console: 
```
Unable to resolve path to module 'axios-cache-interceptor/dev' 
```
If I change the import to `dev/index.bundle` or `dev/index.mjs`, it works. 

(Using `dev/index.cjs` throws `Can't import the named export 'setupCache' (imported as 'setupCache') from default-exporting module (only default export is available)`)

I've no idea why. I do recognize that /dev seems to have exactly the same file names and structure as /dist. I'm used to seeing an `index.js`, which usually allows the package resolver to find something in the directory. But, I don't know if I could just configure my environment to accept .cjs or .mjs as alternate options? 

I'm on Webpack 5.88, which I thought would automatically resolve .mjs types by default? (FWIW, my project was originally setup with Create-React-App, which i know is deprecated/suboptimal, and from which we have ejected. It uses the moduleFileExtensions array in webpack's `resolve.extensions`, and that includes `[ 'web.mjs',  'mjs', 'web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx',]`)

What would help? 
* Config change to my build? 
* Or, do the docs just need an update to suggest using the full manual path? 
* Or is there actually a subtle difference in the structure of the files in /dev that's preventing resolution? 

### axios-cache-interceptor version

1.2.0

### Node / Browser Version

Node v18.15 / Chrome v116

### Axios Version

v1.4.0

### What storage is being used

Memory Storage

### Relevant debugging log output

```js
<none available!>
```

**Comment by arthurfiorette** [comment]
Hey @xml, this pkg seems to be working fine for everyone else, so its safe to assume that its a problem with your build setup. Unfortunately, I do not have any information to help you. However, if you build a reproducible example, I can try to help you out finding the problem...
