### ISSUE TITLE
Adding an IndexedDB Storage

### ISSUE THREAD

**Issue by lucajung** [arthurfiorette/axios-cache-interceptor#669]
Caching huge files which exceed the localstorage (5-10MB) are currently not cacheable.
IndexedDB might be the only solution to cache those responses in modern Web browsers.

**Comment by arthurfiorette** [comment]
Hey! This would be an awesome feature! Up to a PR?

**Comment by lucajung** [comment]
@arthurfiorette With pleasure. How are the PRs handled here?

**Comment by arthurfiorette** [comment]
My only limitation here is to only merge PRs passing CI with added unit tests, anything else should be fine :)

**Comment by lucajung** [comment]
With pleasure. I'll do it in the next couple of days.

**Comment by lucajung** [comment]
Hey! I have it up and running. But there is an issue while writing the key value pair to the database. The set method is only receiving an empty object:  "{\"state\":\"loading\",\"previous\":\"empty\"}"
Do you know what I am doing wrong?
@arthurfiorette

**Comment by arthurfiorette** [comment]
@lucajung Without seeing the code I cannot help with. Open a draft PR please.

**Comment by CatchABus** [comment]
Actually, it's already possible with https://www.npmjs.com/package/idb-keyval which I happen to use for a long time.

**Comment by arthurfiorette** [comment]
https://axios-cache-interceptor.js.org/guide/storages#indexeddb
