### ISSUE TITLE
Bug: TTL doesn't work

### ISSUE THREAD

**Issue by yidongw** [arthurfiorette/axios-cache-interceptor#675]
### What happened?

cache with expired TTL is not deleted

### axios-cache-interceptor version

v1.3.0

### Node / Browser Version

v16.20.0

### Axios Version

v1.4.0

### What storage is being used

Memory Storage

### Relevant debugging log output

```js
cache with expired TTL is not deleted
```

**Comment by arthurfiorette** [comment]
https://axios-cache-interceptor.js.org/guide/storages#memory-storage.

> cleanupInterval: The interval in milliseconds to run a setInterval job of cleaning old entries. If false, the job will not be created. **Disabled is default**
