### ISSUE TITLE
No Effect

### ISSUE THREAD

**Issue by deniapps** [arthurfiorette/axios-cache-interceptor#676]
I incorporated it into the pre-existing axios wrapper, but there doesn't seem to be any noticeable effect. It's possible that I made a mistake somewhere. I haven't observed any logs in the debugging mode. Would you mind reviewing this for me, please?

```
import Axios from "axios";
import { setupCache } from "axios-cache-interceptor/dev";

const axios = Axios.defaults.cache
  ? Axios
  : setupCache(Axios, {
      debug: console.log,
    });

const client = axios.create();

/**
 * Request Wrapper with default success/error actions
 */
const request = function (options) {

  options.headers = {
    "content-type": "application/json",
  };

  if (!/^http/.test(options.url)) {
    options.url = process.env.NEXT_PUBLIC_API_HOST + options.url;
  }
  const onSuccess = function (response) {
    // console.debug("Request Successful!", response);
    return response.data;
  };

  const onError = function (error) {
    // console.error("Request Failed:", error.config);

    if (error.response) {
      // Request was made but server responded with something
      // other than 2xx
      console.error("Status:", error.response.status);
      console.error("Data:", error.response.data);
      // console.error("Headers:", error.response.headers); // hide header
    } else {
      // Something else happened while setting up the request
      // triggered the error
      console.error("Error Message:", error.message);
    }

    return Promise.reject(error.response || error.message);
  };

  return client(options).then(onSuccess).catch(onError);
};

export default request;
```

**Comment by arthurfiorette** [comment]
Hey @deniapps. You are applying the cache to the global axios instance. 

```ts
const client = Axios.create();
const axios = setupCache(client, { debug: console.log });
```

**Comment by deniapps** [comment]
Hello, @arthurfiorette,

Thank you very much! The issue has been resolved on the server-side rendering (SSR) front, but I'm encountering a problem on the client side.

Here's the situation:

When a page loads, it initially makes an API request on the server to fetch the initial data.

Subsequently, based on other factors, the page might make another API request via useEffect on the client side.

The problem arises when the page is reloaded. In this case, I can see that the server-side request correctly pulls data from the cache. However, the client-side request does not utilize the cached data.

Here's a snippet from the log for the first and second reloads:

First Reload:

{id: '**1431042288**', msg: 'Sending request, waiting for response', data: {...}}
{id: '651062088', msg: 'Sending request, waiting for response', data: {...}}
{id: '1431042288', msg: 'Useful response configuration found', data: {...}}
{id: '1431042288', msg: 'Found waiting deferred(s) and resolved them'}
{id: '1431042288', msg: 'Response cached', data: {...}}
{id: '651062088', msg: 'Useful response configuration found', data: {...}}
{id: '651062088', msg: 'Found waiting deferred(s) and resolved them'}
{id: '651062088', msg: 'Response cached', data: {...}}

Second Reload:

{id: '**313497729**', msg: 'Sending request, waiting for response', data: {...}}
{id: '651062088', msg: 'Sending request, waiting for response', data: {...}}
{id: '313497729', msg: 'Useful response configuration found', data: {...}}
{id: '313497729', msg: 'Found waiting deferred(s) and resolved them'}
{id: '313497729', msg: 'Response cached', data: {...}}
{id: '651062088', msg: 'Useful response configuration found', data: {...}}
{id: '651062088', msg: 'Found waiting deferred(s) and resolved them'}
{id: '651062088', msg: 'Response cached', data: {...}}

As you can see, the 651062088 request is being reused, but 313497729 is newly created on the second reload.

Your insights and suggestions on resolving this issue would be greatly appreciated. Thank you!

**Comment by deniapps** [comment]
I think I figured it out.
> A memory storage is the simplest one. It works everywhere and its values are lost upon page reload or when the process is killed.
