### ISSUE TITLE
[Question] Considering 'Accept' header for generating request ID

### ISSUE THREAD

**Issue by CatchABus** [arthurfiorette/axios-cache-interceptor#729]
There's been a case when I have to consider the `Accept` header of a request for caching.
Package has support for custom key generation but at the same time I want to use the default formula.

I came up with this:
```js
setupCache(axios, {
  generateKey: buildKeyGenerator((request) => {
    let id = defaultKeyGenerator(request);
    if (request.headers["Accept"]) {
      return `${id}-${request.headers["Accept"]}`;
    }
    return id;
  })
});
```
My question is whether this is going against of how the key API should be used, and if my approach might stop being functional at one point. Also, is there any consideration for generator to take certain headers like `Accept` into account?

**Comment by arthurfiorette** [comment]
This is fine and will work just as any other way. You could also return an object and let the key generator hash it for you.

https://axios-cache-interceptor.js.org/guide/request-id#custom-generator
