### ISSUE TITLE
Optimization: Reduce cache calls

### ISSUE THREAD

**Issue by paescuj** [arthurfiorette/axios-cache-interceptor#747]
### What happened?

Thank you very much for this library!

I've done some debugging and noticed there are quite a few cache calls happening for the following scenario:
There's a response in cache which is stale (max-age reached) and it gets re-validated.

I'm wondering whether those could actually be reduced.

I would have expect two cache calls for such a case:
- _Cache Call 1:_ `find` to get cached response
- Do request to revalidate
- _Cache Call 2:_ `set` to update the cached response

In fact, 5 calls are made (see the log below, logged as `cache: ...`).
I guess that's because request configs are updated and written back to cache again before the actual request is carried out. Couldn't that happen in-memory and only be written down to the cache after processing the new request?

### axios-cache-interceptor version

v1.3.2

### Node / Browser Version

Node.js v18.19.0

### Axios Version

v1.6.2

### What storage is being used

Another one

### Relevant debugging log output

```js
cache: find (key: 1137762219)
cache: set (key: 1137762219)
cache: set (key: 1137762219)
{ id: '1137762219', msg: 'Updated stale request' }
{
  id: '1137762219',
  msg: 'Sending request, waiting for response',
  data: { overrideCache: false, state: 'stale' }
}
cache: find (key: 1137762219)
{
  id: '1137762219',
  msg: 'Useful response configuration found',
  data: {
    cacheConfig: {
      update: {},
      ttl: 300000,
      methods: [Array],
      cachePredicate: [Object],
      etag: true,
      modifiedSince: false,
      interpretHeader: true,
      cacheTakeover: true,
      staleIfError: true,
      override: false,
      hydrate: undefined
    },
    cacheResponse: {
      data: [Object],
      status: 200,
      statusText: 'OK',
      headers: [Object]
    }
  }
}
{
  id: '1137762219',
  msg: 'Found waiting deferred(s) and resolved them'
}
cache: set (key: 1137762219)
{
  id: '1137762219',
  msg: 'Response cached',
  data: {
    cache: {
      state: 'cached',
      ttl: 89000,
      staleTtl: undefined,
      createdAt: 1702166521005,
      data: [Object]
    },
    response: {
      status: 200,
      statusText: 'OK',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object],
      id: '1137762219',
      cached: true
    }
  }
}
```

**Comment by arthurfiorette** [comment]
Hey @paescuj is this directly impacting the performance of your app? Request and response in axios should have completely separated state from each other, that's why two finds happen.

Let me walk you through what
