### ISSUE TITLE
Feature requests: Stats of storage, memory size

### ISSUE THREAD

**Issue by chaoyangnz** [arthurfiorette/axios-cache-interceptor#783]
We need to trace how much memory is used for MemoryStorage, hopefully it can report the stats so that we can tweak the config, max entries

**Comment by arthurfiorette** [comment]
Hey @chaoyangnz, you will need to implement your own memory storage to be able to do this. Hopefully you won't have any trouble as it is a basic implementation: https://github.com/arthurfiorette/axios-cache-interceptor/blob/main/src/storage/memory.ts.

I'd love to hear what you could achieve and maybe this becomes a native feature :)
