### ISSUE TITLE
Bug: CORS Error using setupCache

### ISSUE THREAD

**Issue by mehranml** [arthurfiorette/axios-cache-interceptor#787]
### What happened?

A bug happened!
as i change my default axios instance to setupCache setup i get CORS error on sending GET request to https://api.raydium.io/v2/sdk/farm-v2/mainnet.json

### axios-cache-interceptor version

1.5.1

### Node / Browser Version

20.10

### Axios Version

1.6.7

### What storage is being used

Web Storage

### Relevant debugging log output

```js
Third-party cookie will be blocked. Learn more in the Issues tab.
4
Access to XMLHttpRequest at 'https://api.raydium.io/v2/sdk/farm-v2/mainnet.json' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by arthurfiorette** [comment]
https://axios-cache-interceptor.js.org/config/request-specifics#cache-cachetakeover

![image](https://github.com/arthurfiorette/axios-cache-interceptor/assets/47537704/48c83030-59e1-43f8-bf36-3b184366590a)

![image](https://github.com/arthurfiorette/axios-cache-interceptor/assets/47537704/8bd7583a-b586-4222-8c93-6e70413bb0f8)
