### ISSUE TITLE
Cache collisions detected with defaultKeyGenerator, at the level of 100K cache keys

### ISSUE THREAD

**Issue by giorgiosironi** [arthurfiorette/axios-cache-interceptor#795]
### What happened?

We use a custom redis storage copied from the documentation, and after ~100K cache keys are stored we [started seeing collisions where requests to different APIs and URLs are cached on the same key](https://github.com/sciety/sciety/issues/3018). 

The hash looks like a 32-bit value so (with some assumptions) the [probability of collisions](https://preshing.com/20110504/hash-collision-probabilities/) is 50% with about 77K values.

We are now replacing the default with a key based on the URL plus other application-specific assumptions like headers.

It might be useful to make the hashing function replaceable so that for example it can be swapped with MD5 which is 128-bit long.

We also looked into detecting a cache collision, but the original request is not stored in the cache; as such a cached value cannot be compared with a new request to check whether it matches upon being found via the cache key, like it would happen in a hash table.

### axios-cache-interceptor version

v1.5.1

### Node / Browser Version

18.18

### Axios Version

v1.6.7

### What storage is being used

Redis / Other DB

### Relevant debugging log output

```js
sciety--prod--cache:6379> KEYS *
...
131147) "axios-cache-1497324604"
131148) "axios-cache-1168472422"
131149) "axios-cache--1450800637"
131150) "axios-cache--1612341055"
(0.88s)
# where `-1612341055` is the key being produced by the library with the help of `object-code`
```

**Comment by arthurfiorette** [comment]
> It might be useful to make the hashing function replaceable so that for example it can be swapped with MD5 which is 128-bit long.

You already can: https://axios-cache-interceptor.js.org/config#generatekey

---

I think this collision probability is fair to a [496b implementation](https://www.npmjs.com/package/object-code) which is crucial to reduce the bundle size overall. Also, most common usage is in web browsers, which has a low MB quota per website.

I'll add a mention on the docs about this issue when `axios-cache-interceptor` is used in large scale.
