### ISSUE TITLE
useCache method name is confusing since 'use' is a reserved prefix for React hooks

### ISSUE THREAD

**Issue by vinnieking06** [arthurfiorette/axios-cache-interceptor#95]
React and my linter think that it's a react hook, so I get a linting error and displayed below. I can resolve by aliasing the import name, but it would be preferable for React devs to use a different name for the primary method.

Thank you for building this great package!
![Screen Shot 2021-12-27 at 9 57 56 AM](https://user-images.githubusercontent.com/18544837/147492248-7acdba78-ea20-4872-9a84-d26708f52209.png)

**Comment by arthurfiorette** [comment]
Hi!
Before, there was a createCache function and a useCache. A while ago I removed the createCache function and left only useCache, but for an outsider's perspective it makes a lot more sense for the function name to be changed. It makes total sense, thanks!

**Comment by arthurfiorette** [comment]
I published `v0.7.7` to fix this issue for you. You can close this issue if it does not need anything more. 🚀

**Comment by vinnieking06** [comment]
awesome, thanks so much @arthurfiorette!!
